### ISSUE TITLE
0_train-cnn/input/images.npy not accessible

### ISSUE THREAD

**Issue by bluepotatoes** [dillanchang/deep-phase-imaging#1]
Hello,

I was hoping to run the model to see whether my GPU is capable of these sorts of calculations, but `0_train-cnn/input/images.npy` cannot be downloaded because the repo is over its data limit. 

Would it be possible for you to host that file with a google drive, box, or zenodo link? Or should I scrape the web for images myself? 

Any input appreciated. Thank you.

**Comment by dillanchang** [comment]
Hi bluepotatoes,
All of the input files can be found here:
https://drive.google.com/drive/folders/12nNB5n-v5GIBEmmBy7JW9ob3wYYL63tj?usp=sharing
